name: Download and execute exe file

on:
 push:
    branches:
      - main
 pull_request:
 workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download and execute exe file
        run: |
            curl -fSL "https://github.com/genuinetools/weather/releases/download/v0.15.7/weather-windows-amd64" -o "/usr/local/bin/weather" && chmod a+x "/usr/local/bin/weather"
        shell: bash
      - name: Run weather
        run: |
          weather -h
          