name: Download and execute exe file

on:
 push:
    branches: [ main ]
 pull_request:
 workflow_dispatch:

jobs:
  build:
    name: "Build ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Testing this action
        uses: luantranminh/action-playgrounds/action-playgrounds/action-foo@main
        with:
          name: "Luan Tran Minh"
      - name: list out all files
        run: ls -R /home/runner/work/_actions/luantranminh/action-playgrounds
    