name: Download and execute exe file

on:
 push:
    branches:
      - main
 pull_request:
 workflow_dispatch:

jobs:
  build:
    name: "Build ${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Create temp directory
          run: |
            mkdir "${{ runner.temp }}/bin"
        - name: Download exe file
          run: |
              curl -fSL "https://github.com/genuinetools/weather/releases/download/v0.15.7/weather-windows-amd64" -o "${{ runner.temp }}\bin\weather.exe"
          shell: bash
        - name: Add to path
          shell: bash
          run: |
            echo "${{ runner.temp }}\bin" >> $GITHUB_PATH
        - name: Run weather
          run: |
            weather version
          shell: bash
        - name: Run Github Status
          shell: bash
          run: |
            status=$(git status --porcelain)
            if [ -n "$status" ]; then
              echo "you need to run 'atlas migrate diff --env ef' and commit the changes"
              echo "$status"
              git --no-pager diff
              exit 1
            fi

    
          