name: Download and execute exe file

on:
 push:
    branches:
      - main
 pull_request:
 workflow_dispatch:

jobs:
  build:
    name: "Build ${{ matrix.os }}"
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - name: Check PR title
          run: |
            title="${{ github.event.pull_request.title }}"
            if [[ "$title" != *"[build]"* ]]; then
              echo "PR title does not contain '[build]'"
              exit 1
            fi