name: Atlas
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  plan:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_0FIE2F }}
      - uses: ariga/atlas-action/schema/plan@master
        with:
          from: env://url
          schema-name: a8m-app
          dev-url: 'sqlite://dev?mode=memory'
          config: 'file://atlas.hcl'
          env: 'prod'
  apply:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_0FIE2F }}
      - uses: ariga/atlas-action/schema/push@master
        with:
          dev-url: 'sqlite://dev?mode=memory'
          schema-name: a8m-app
          config: 'file://atlas.hcl'
          env: 'prod'
      - uses: ariga/atlas-action/schema/plan/approve@master
        id: plan-approve
        with:
          from: env://url
          to: ${{ steps.schema-push.outputs.url }}
          dev-url: 'sqlite://dev?mode=memory'
          schema-name: a8m-app
          config: 'file://atlas.hcl'
          env: 'prod'
      - uses: ariga/atlas-action/schema/apply@master
        if: ${{ steps.plan-approve.outputs.status == 'APPROVED' }}
        with:
          dev-url: 'sqlite://dev?mode=memory'
          config: 'file://atlas.hcl'
          env: 'prod'
          plan: ${{ steps.plan-approve.outputs.plan }}