name: Atlas
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  plan:
    if: ${{ github.event_name == 'pull_request' }}
    services:
      # Spin up a mysql:8 container to be used as the dev-database for analysis.
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: dev
          MYSQL_ROOT_PASSWORD: pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_U8933W }}
      - uses: ariga/atlas-action/schema/plan@master
        with:
          dev-url: 'mysql://root:pass@localhost:3306/dev'
          config: 'file://atlas.hcl'
          env: 'GORM_MIGRATION_SOURCE'
        env:
          GITHUB_TOKEN: ${{ github.token }}
  apply:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    services:
      # Spin up a mysql:8 container to be used as the dev-database for analysis.
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: dev
          MYSQL_ROOT_PASSWORD: pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_U8933W }}
      - uses: ariga/atlas-action/schema/push@master
        with:
          dev-url: 'mysql://root:pass@localhost:3306/dev'
          config: 'file://atlas.hcl'
          env: 'GORM_MIGRATION_SOURCE'
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: ariga/atlas-action/schema/plan@master
        id: schema-plan
        with:
          from: env://url
          to: atlas://bc/triggers.my
          dev-url: 'mysql://root:pass@localhost:3306/dev'
          config: 'file://atlas.hcl'
          env: 'GORM_MIGRATION_SOURCE'
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: ariga/atlas-action/schema/apply@master
        if: ${{ steps.schema-plan.outputs.status == 'APPROVED' }}
        with:
          dev-url: 'mysql://root:pass@localhost:3306/dev'
          config: 'file://atlas.hcl'
          env: 'GORM_MIGRATION_SOURCE'
          plan: ${{ steps.schema-plan.outputs.plan }}
        env:
          GITHUB_TOKEN: ${{ github.token }}