name: Atlas
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  plan:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_2A9PVH }}
      - uses: ariga/atlas-action/schema/plan@master
        with:
          from: sqlite://file?mode=memory
          to: file://schema-1.lt.hcl
          schema-name: app
          dev-url: 'sqlite://dev?mode=memory'
  apply:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_2A9PVH }}
      - uses: ariga/atlas-action/schema/push@master
        id: schema-push
        with:
          dev-url: 'sqlite://dev?mode=memory'
          url: file://schema-1.lt.hcl
          schema-name: app
      - uses: ariga/atlas-action/schema/plan/approve@master
        id: plan-approve
        with:
          from: sqlite://file?mode=memory
          to: ${{ steps.schema-push.outputs.url }}
          dev-url: 'sqlite://dev?mode=memory'
          schema-name: app
      - uses: ariga/atlas-action/schema/apply@master
        if: ${{ steps.plan-approve.outputs.status == 'APPROVED' }}
        with:
          url: sqlite://file?mode=memory
          dev-url: 'sqlite://dev?mode=memory'
          plan: ${{ steps.plan-approve.outputs.plan }}