name: Atlas
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  plan:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_4E54M0 }}
      - uses: ariga/atlas-action/schema/plan@v1
        with:
          from: musq
          to: file
          schema-name: app
          dev-url: 'sqlite://dev?mode=memory'
          config: 'file://atlas.hcl'
  apply:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_4E54M0 }}
      - uses: ariga/atlas-action/schema/push@v1
        id: schema-push
        with:
          dev-url: 'sqlite://dev?mode=memory'
          url: file
          schema-name: app
          config: 'file://atlas.hcl'
      - uses: ariga/atlas-action/schema/plan/approve@v1
        id: plan-approve
        with:
          from: musq
          to: ${{ steps.schema-push.outputs.url }}
          dev-url: 'sqlite://dev?mode=memory'
          schema-name: app
          config: 'file://atlas.hcl'
      - uses: ariga/atlas-action/schema/apply@v1
        if: ${{ steps.plan-approve.outputs.status == 'APPROVED' }}
        with:
          url: musq
          to: file
          dev-url: 'sqlite://dev?mode=memory'
          config: 'file://atlas.hcl'
          plan: ${{ steps.plan-approve.outputs.plan }}