name: Atlas
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  plan:
    if: ${{ github.event_name == 'pull_request' }}
      - uses: ariga/atlas-action/schema/plan@v1
        with:
          config: 'file://hoho/atlas.hcl'
          env: 'sd'
  apply:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - uses: ariga/atlas-action/schema/push@v1
        id: schema-push
        with:
          config: 'file://hoho/atlas.hcl'
          env: 'sd'
      - uses: ariga/atlas-action/schema/plan/approve@v1
        id: plan-approve
        with:
          to: ${{ steps.schema-push.outputs.url }}
          config: 'file://hoho/atlas.hcl'
          env: 'sd'
      - uses: ariga/atlas-action/schema/apply@v1
        if: ${{ steps.plan-approve.outputs.status == 'APPROVED' }}
        with:
          config: 'file://hoho/atlas.hcl'
          env: 'sd'
          plan: ${{ steps.plan-approve.outputs.plan }}