name: CD/VSCode - Marketplace
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci
      
      - name: Get Version
        id: package-version
        working-directory: packages/vscode
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Create and push tag
        if: success()
        run: |
          git tag -a "vscode-ext@v${{ steps.package-version.outputs.version }}" -m "Release vscode-ext@v${{ steps.package-version.outputs.version }}"
          git push origin "vscode-ext@v${{ steps.package-version.outputs.version }}"
      
